source: site
paths:
  uploads: uploads
  dam_uploads: ''
  static: ''
  dam_static: ''
  collections: collections
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: collections/_posts
    output: true
    icon:
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/post.md
  pages:
    path: collections/_pages
    output: true
    icon: wysiwyg
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/page.html
  projects:
    path: collections/_projects
    output: true
    description: ''
    icon: work_outline
    preview:
      text:
      subtext:
        - key: subtitle
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/project.md
  testimonials:
    path: collections/_testimonials
    output: false
    description: ''
    icon: format_quote
    sort:
      key: name
    sort_options:
      - key: name
      - key: name
        order: desc
      - key: position
      - key: position
        order: desc
    preview:
      text:
      subtext:
        - key: position
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _editables:
    _enabled_editors:
      - data
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/testimonial.md
  drafts:
    path: collections/_drafts
    output: true
    icon:
    create:
      publish_to: posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
collection_groups:
  - heading: Content
    collections:
      - pages
      - projects
      - testimonials
  - heading: Blogging
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data
_inputs:
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_structures:
  content_blocks:
    style: modal
data_config: true
timezone: Etc/UTC
